#!/usr/bin/env bash

###############
## VARIABLES ##
###############

# Create timestamp for log file
timestamp=$(date +"%Y-%m-%d_%H:%M:%S")

# Save current user's username to variable
username="$(whoami)"

#################
## MAIN SCRIPT ##
#################

# Run script that corresponds to arch or debian and stream output to a log file
echo "LINUX SETUP SCRIPT FOR ARCH AND DEBIAN LINUX DISTRIBUTIONS"
sleep 2
mkdir -p logs # Make sure logs directory exists
if [[ -f /etc/os-release || -n "$1" ]]; then
    source /etc/os-release
    if [[ $ID_LIKE =~ "arch" || "$1" == "arch" ]]; then
        sudo scripts/setup-arch $username | tee logs/${timestamp}_setup.log
    elif [[ $ID_LIKE =~ "debian" || "$1" == "debian" ]]; then
        sudo scripts/setup-debian $username | tee logs/${timestamp}_setup.log
    elif [[ -n "$1" && "$1" != "arch" && "$1" != "debian" ]]; then
        echo "[SETUP_ERROR] : Unsupported distribution variable provided. Variable can either be \"arch\" or \"debian\"."
        exit 1
    else
        echo "[SETUP_ERROR] : Unknown distribution in ID_LIKE. Provide arch or debian as a variable, if you know it applies to your distribution. For example: ./setup \"arch\""
        exit 1
    fi
else
    echo "[SETUP_ERROR] : /etc/os-release not found. Provide arch or debian as a variable, if you know it applies to your distribution. For example: ./setup \"arch\""
    exit 1
fi

#######################
## POST SCRIPT TASKS ##
#######################

if [[ $? = 0 ]]; then
    # Execute zsh
    echo "[SETUP_INFO] : Executing zsh on current user..."
    exec zsh

    echo "SETUP FINISHED"
    echo "The following post setup tasks should still be done:"
    echo "1. If i3 installed correctly, you should be able to logout of your current session and then choose i3 in the login screen."
    echo "    - Does not apply, if i3 was already installed. Restart i3 with \"shift+mod r\"."
    echo "    - If your distribution did not have desktop environment or window manager before, you can start i3 by running the command \”i3\"."
    echo "2. If a firewall was already installed, check its rules."
    echo "3. Open tmux session with the command \"tmux\" and install tmux plugins by pressing \"ctrl+space I\"."
    echo "3. Open neovim once with command \"nvim\" and let it install all the plugins."
    echo "5. If everything works, you can remove the old backup directories of configurations from \"~/.config\". if you want to."
else
    echo "[SETUP_ERROR] : Script was interrupted by an unexpected error."
fi
