#!/usr/bin/env bash

basic_packages=(
    "git"
    "curl"
    "wget"
    "sed"
    "awk"
    "grep"
    "rsync"
    "inetutils" # telnet
    "openbsd-netcat"
    "openssh"
    "stow"
    "python"
    "neofetch"
    "htop"
    "eza"
    "bat"
    "git-delta"
    "zoxide"
    "vim"
    "neovim"
    "tmux"
    "fzf"
    "fd"
    "ripgrep"
    "xclip"
    "tldr"
    "thefuck"
    "entr"
    "ffmpeg"
    "pnpm"
)

basic_packages_yay=(
    "azure-cli"
    "flyctl"
    "python-pipx"
)

apps=(
    "kitty"
    "firefox"
    "thunar"
    "discord"
    "thunderbird"
)

apps_yay=(
    "spotify"
    "bitwarden"
    "signal-desktop"
    "whatsapp-for-linux"
)

i3_packages=(
    "i3-wm"
    "i3blocks"
    "gtk2"
    "gtk3"
    "gtk4"
    "gnome-themes-extra"
    "catppuccin-gtk-theme-mocha"
    "qogir-gtk-theme"
    "qogir-icon-theme"
    "otf-firamono-nerd"
    "arandr"
    "dex"
    "feh"
    "picom"
    "dunst"
    "rofi"
    "playerctl"
    "scrot"
    "polkit-gnome"
    "autotiling"
    "blueberry"
)

i3_packages_yay=(
    "xorg-xset"
    "xorg-xrandr"
    "rofi-greenclip"
    "bitwarden-rofi" #???
    "alsa-utils" # amixer
    "network-manager-applet "
)
