#!/usr/bin/env bash

# NOTE: The following packages are handled by justfile recipes (justfile install) in the dotfiles repository:
# Core tools: git, curl, stow, vim, neovim, tmux, zsh, fzf, fd-find, ripgrep, xclip, wl-clipboard
# Development: nodejs, npm, python3, build-essential, cmake
# CLI tools: eza, bat, git-delta, zoxide, starship, btop, entr, jq, thefuck, tldr
# Utilities: ffmpeg, p7zip-full, poppler-utils, imagemagick
# DevOps: terraform, ansible, kubectl, helm
# Shell: zsh-plugins, atuin history import, shell switching
# Applications: lazygit, yazi, atuin
# Font: JetBrainsMono Nerd Font (downloaded from nerd-fonts releases)
# Linters & formatters: installed in NeoVim via :MasonInstall shellcheck shfmt stylua prettier ruff hadolint tflint ansible-lint
# See: https://github.com/Aapok0/dotfiles
#
# Packages kept here are those needed BEFORE running justfile or not included in justfile

apt_tools=(
    "nala"
    "apt-listbugs"
    "apt-listchanges"
    "apt-file"
)

basic_packages=(
    "git"
    "just"
    "curl"          # Needed for various installations
    "wget"
    "sed"
    "gawk"
    "grep"
    "rsync"
    "inetutils-tools"
    "netcat-openbsd"
    "dnsutils"
    "openssh-client"
    "unzip"
    "unrar"
    "python3-tk"
    "pnpm"
    "fastfetch"
    "exfatprogs"
    "smartmontools"
    "fwupd"
    "snapper"
    "btrfs-progs"
)

basic_packages_pip=(
    "azure-cli"
    "python3-pip"
    "python3-pipx"
    "protonup-qt"
)

apps=(
    "firefox-esr"
    "discord"
    "thunderbird"
    "mpv"
    "vlc"
    "qalculate-gtk"
    "openrgb"
    "virtualbox"
    "virtualbox-guest-utils"
    "qbittorrent"
)

apps_extra=(
    "spotify-client"
    "bitwarden"
    "signal-desktop"
    "onlyoffice-desktopeditors"
)

gaming_packages=(
    "steam"
    "lutris"
    "wine"
    "wine32"
    "wine-development"
    "winetricks"
    "mangohud"
    "gamemode"
    "joystick"
)

gaming_packages_extra=(
    "protontricks"
    "steamtinkerlaunch"
)

kde_packages=(
    "kde-full"
    "kscreen"
    "kcron"
    "ark"
    "plasma-nm"
    "plasma-pa"
    "power-profiles-daemon"
    "bluedevil"
    "ibus"
    "dolphin"
    "kdegraphics-thumbnailers"
    "ffmpegthumbs"
    "flatpak"
    "discover"
    "spectacle"
)

kde_packages_extra=()
